plugins:
  - jasmine
  - node
env:
  browser: true
  commonjs: true
  es6: true
  jasmine: true
  node: true
extends:
  - 'eslint:recommended'
parserOptions:
  ecmaVersion: 2015
rules:
  indent:
    - error
    - tab
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-console:
    - error
    - allow:
      - log
